### ISSUE TITLE
changes required to install properly

### ISSUE THREAD

**Issue by rcampbel3** [Netflix-Skunkworks/bpftoolkit#1]
Hi Brendan,

I just checked out the repo, cd'd into it and did a ```git submodule update --init --recursive```
Then tried to run ```./scripts/setup.bash``` and hit a few minor issues...

I had to do the following to get ./scripts/setup.bash to complete properly:

```bash
ln -s submodules/bcc .
ln -s submodules/bpftrace .
mkdir -p pub/disks
```

Thanks!

**Comment by gmunoz** [comment]
@rcampbel3 Thanks for the heads up. I pushed some updates that should include the correct file paths in https://github.com/Netflix-Skunkworks/bpftoolkit/commit/c63fabbeba9ef847ef196f52c6bc58258590a0ea. And I think the pub/disks was an unexpected name so I switched that up to be pub/disk to match the rest of commands that are like it.
